// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDumJ3vrEePWOGbBq6zMOB3CapuVf4_34U',
    appId: '1:982132430995:android:5bd3589122d173c02c5566',
    messagingSenderId: '982132430995',
    projectId: 'smart-sense-tutor',
    storageBucket: 'smart-sense-tutor.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiDyBzj83PmjDWbjUzLtgdo177s7ZvgdU',
    appId: '1:982132430995:web:737d132d956640d82c5566',
    messagingSenderId: '982132430995',
    projectId: 'smart-sense-tutor',
    authDomain: 'smart-sense-tutor.firebaseapp.com',
    storageBucket: 'smart-sense-tutor.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiDyBzj83PmjDWbjUzLtgdo177s7ZvgdU',
    appId: '1:982132430995:web:737d132d956640d82c5566',
    messagingSenderId: '982132430995',
    projectId: 'smart-sense-tutor',
    authDomain: 'smart-sense-tutor.firebaseapp.com',
    storageBucket: 'smart-sense-tutor.firebasestorage.app',
  );
}
