// lib/main.dart
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by the FlutterFire CLI configuration tool
import 'package:firebase_auth/firebase_auth.dart';

import 'homescreen.dart';
import 'account/auth_screen.dart'; // Verified absolute import targeting your auth folder path
import 'services/quiz_engine.dart';
import 'progress.dart';
import 'analyzer/polysemy_analyzer.dart';

Future<void> main() async {
  // Guard clause to ensure native plugin channel links are established
  WidgetsFlutterBinding.ensureInitialized();

  // 1. Initialize Firebase Core Engine using your platform credentials
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // 2. Load your existing native app engines and CSV dataset frameworks
  await QuizEngine.instance.initialize();
  await PolysemyAnalyzer.loadDataset();

  runApp(const WSDGameApp());
}

class WSDGameApp extends StatelessWidget {
  const WSDGameApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Smart Sense Tutor',
      theme: ThemeData(
        scaffoldBackgroundColor: Colors.white,
        primaryColor: const Color(0xFF70D3F4),
      ),
      // Use the AuthGate checker as our true initial launch viewport parameter
      home: const AuthGate(),
    );
  }
}

/// Listens to the current user stream session on app startup
/// to route the player seamlessly without broken transition buffers.
class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // While Firebase verifies token states, render a clean background loader
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(
              child: CircularProgressIndicator(
                valueColor: AlwaysStoppedAnimation<Color>(Color(0xFF70D3F4)),
              ),
            ),
          );
        }

        // Check if a verified user token is saved inside local secure hardware
        if (snapshot.hasData && snapshot.data != null) {
          return FutureBuilder(
            // Pre-fetch the cloud save file mapping variables into Singleton memory
            future: ProgressService().downloadProgressFromCloud(),
            builder: (context, syncSnapshot) {
              // Wait for user cloud configurations to resolve before loading views
              if (syncSnapshot.connectionState == ConnectionState.waiting) {
                return const Scaffold(
                  body: Center(
                    child: CircularProgressIndicator(
                      valueColor: AlwaysStoppedAnimation<Color>(Color(0xFF70D3F4)),
                    ),
                  ),
                );
              }
              // Cloud progress successfully recovered; display the welcoming intro
              return const IntroScreen();
            },
          );
        }

        // If no user object exists, display your custom clean AuthScreen view directly
        return const AuthScreen();
      },
    );
  }
}

class IntroScreen extends StatelessWidget {
  const IntroScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: SafeArea(
        child: SizedBox(
          width: double.infinity,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              const Text(
                "Welcome to",
                style: TextStyle(
                  fontSize: 28,
                  fontWeight: FontWeight.bold,
                  color: Color(0xFF2C4379),
                  fontFamily: 'Sans-Serif',
                ),
              ),
              const SizedBox(height: 20),

              Image.asset(
                'asset/logo.png',
                width: 320,
                fit: BoxFit.contain,
                errorBuilder: (c, e, s) => const Icon(Icons.menu_book, size: 100, color: Color(0xFF70D3F4)),
              ),

              const SizedBox(height: 40),

              const Padding(
                padding: EdgeInsets.symmetric(horizontal: 40),
                child: Text(
                  "Grow your vocabulary, expand your world.",
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    fontSize: 14,
                    color: Colors.black87,
                  ),
                ),
              ),

              const SizedBox(height: 40),

              TextButton(
                onPressed: () {
                  Navigator.pushReplacement(
                    context,
                    MaterialPageRoute(
                      builder: (context) => const HomeScreen(),
                    ),
                  );
                },
                child: Text(
                  "Tap anywhere to start",
                  style: TextStyle(
                    color: Colors.grey[400],
                    fontSize: 14,
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}